#!/bin/sh

export USAGE="Usage: mkboardbook dest. Creates boardbook.zip in the temporary directory"
export TMPDIR="$1"


if [ "$#" -gt 1 ]
then 
 echo $USAGE; exit 1
fi

echo "Saving to $TMPDIR/boardbook.zip"

rsync -a * $TMPDIR
cd $TMPDIR
find . -name "*.md" -execdir ./convertmd {} \; -execdir rm {} \;
find . -name


#zip -r boardbook *


	    

