name: Generate a board book for a given meeting (identified by folder name).

on:
  workflow_dispatch:
    inputs:
      group:
        description: 'Board or committee'
        required: true
        type: choice
        options:
          - board
          - governance
          - finance
          - personnel
          - development
      folder:
        description: 'Folder name'
        required: true
        type: string

jobs:
 create-boardbook:
   name: Create a zip file of meeting materials
   runs-on: ubuntu-latest
   steps:
     - name: Checkout latest version of repo
       uses: actions/checkout@v3
       with:
         ref: main

     - name: Install pandoc to turn md to html
       uses: pandoc/actions/setup@main

     - name: Add scripts to path for subsequent steps
       run: echo ${{ github.workspace }}/scripts >> ${{ github.path }}

     - name: Make book
       shell: bash
       run: |
         mkdir output
         rsync -a board/meetings/${{ inputs.group }}/${{ inputs.folder }}/* output
         find output -name "*.md" -execdir convertmd {} \; -execdir rm {} \;
         cd output
         zip r boardbook *


      - name: Provide access to boardbook.zip
        uses: actions/upload-artifact@v4
        with:
          name: boardbook.zip
          path: output
          retention-days: 1 